config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-web:
      branch: dev-diana
      deploy_template: .sqa/docker-compose.yml
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_DOCKERSERVER: https://hub.docker.com/
sqa_criteria:
  qc_doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - pwd
        container: node
timeout: 600
