config:
  credentials: []
  project_repos:
    sqaaas-web:
      branch: master
      deploy_template: .sqa/docker-compose.yml
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_DOCKERSERVER: https://hub.docker.com/
sqa_criteria:
  qc_doc:
    repos:
      sqaaas-web:
        commands:
        - npm -l
        container: node
timeout: 600
